version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    reviewers:
      - multani
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
